{% set name = "gmmlib" %}
{% set version = "19.3.4" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/intel-gmmlib-{{ version }}.tar.gz
  sha256: 5f08e36892db6bff8284913d9ab784f693d50e4ea1eb2ea6d2545e3dc6876b71

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: 'Intel(R) Graphics Memory Management Library'

extra:
  recipe-maintainers:
    - isuruf
