{% set name = "gmmlib" %}
{% set version = "19.4.1" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/intel-gmmlib-{{ version }}.tar.gz
  sha256: bb874b41c499abb8f6253b1834e93a02ed9744de71f2503ee9cd4100af7c1860

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: 'Intel(R) Graphics Memory Management Library'

extra:
  recipe-maintainers:
    - isuruf
