{% set name = "gmmlib" %}
{% set version = "22.4.1" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-{{ version }}.tar.gz
  sha256: 451fbe2eac26533a896ca0da0356354ecc38680f273fce7d121c6a22251ed21e

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: Intel(R) Graphics Memory Management Library

extra:
  recipe-maintainers:
    - isuruf
