{% set name = "gmmlib" %}
{% set version = "22.3.20" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-{{ version }}.tar.gz
  sha256: 227c1614d4817154b4e6fbfb667ba2b231ea7aa53796d91f1800af9aeb703f59

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: Intel(R) Graphics Memory Management Library

extra:
  recipe-maintainers:
    - isuruf
