{% set name = "gmmlib" %}
{% set version = "22.3.17" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-{{ version }}.tar.gz
  sha256: 5fa23407d4780c4ee8acd68e9ec9186e1721238150dc36ca9ab469a335891d2a

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: Intel(R) Graphics Memory Management Library

extra:
  recipe-maintainers:
    - isuruf
